### ISSUE TITLE
When putting special charachters in answers , design is corrupted and next question isn't shown

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Kenya_InstantWin#69]
From UI 
![image](https://user-images.githubusercontent.com/44364394/48857076-b6223900-edc0-11e8-99e4-75742def45b9.png)
From DB 
![image](https://user-images.githubusercontent.com/44364394/48857133-d94ce880-edc0-11e8-9792-c568f485a8d4.png)

**Comment by alweshahi** [comment]
Kindly note that the * astrick  character is forbidden as we use the astrick in the code.
